# flake8: noqa  # generated protobuf output
# Copyright 2024 Tier IV, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated from autoware_bridge/proto/autoware_bridge.proto -- do not edit.
# The .proto is vendored verbatim from hakuturu583/autoware_lanelet2_to_opendrive
# (autoware_carla_scenario/proto/autoware_bridge/v0); its `package` is kept so the
# gRPC service name matches the scenario-library server this client dials.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

from autoware_carla_interface.autoware_bridge.proto import (
    autoware_bridge_pb2 as autoware__bridge__pb2,
)
import grpc


class AutowareBridgeStub(object):
    """-- Service ----------------------------------------------------------------

    Hosted by the scenario library; the autoware_carla_interface node is the
    client (see the topology note above).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMission = channel.unary_unary(
            "/autoware_carla_scenario.autoware_bridge.v0.AutowareBridge/GetMission",
            request_serializer=autoware__bridge__pb2.GetMissionRequest.SerializeToString,
            response_deserializer=autoware__bridge__pb2.GetMissionResponse.FromString,
        )
        self.ReportReadiness = channel.unary_unary(
            "/autoware_carla_scenario.autoware_bridge.v0.AutowareBridge/ReportReadiness",
            request_serializer=autoware__bridge__pb2.ReportReadinessRequest.SerializeToString,
            response_deserializer=autoware__bridge__pb2.ReportReadinessResponse.FromString,
        )


class AutowareBridgeServicer(object):
    """-- Service ----------------------------------------------------------------

    Hosted by the scenario library; the autoware_carla_interface node is the
    client (see the topology note above).
    """

    def GetMission(self, request, context):
        """Fetch the scenario's mission (initial pose + goal). The client polls this
        until `available`; the Autoware side then auto-initializes, routes, and
        engages from it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReportReadiness(self, request, context):
        """Report the single readiness flag once Autoware is initialized, routed,
        engaged, and driving. The framework latches it so the entity can poll it
        per tick.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AutowareBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetMission": grpc.unary_unary_rpc_method_handler(
            servicer.GetMission,
            request_deserializer=autoware__bridge__pb2.GetMissionRequest.FromString,
            response_serializer=autoware__bridge__pb2.GetMissionResponse.SerializeToString,
        ),
        "ReportReadiness": grpc.unary_unary_rpc_method_handler(
            servicer.ReportReadiness,
            request_deserializer=autoware__bridge__pb2.ReportReadinessRequest.FromString,
            response_serializer=autoware__bridge__pb2.ReportReadinessResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "autoware_carla_scenario.autoware_bridge.v0.AutowareBridge", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class AutowareBridge(object):
    """-- Service ----------------------------------------------------------------

    Hosted by the scenario library; the autoware_carla_interface node is the
    client (see the topology note above).
    """

    @staticmethod
    def GetMission(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/autoware_carla_scenario.autoware_bridge.v0.AutowareBridge/GetMission",
            autoware__bridge__pb2.GetMissionRequest.SerializeToString,
            autoware__bridge__pb2.GetMissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ReportReadiness(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/autoware_carla_scenario.autoware_bridge.v0.AutowareBridge/ReportReadiness",
            autoware__bridge__pb2.ReportReadinessRequest.SerializeToString,
            autoware__bridge__pb2.ReportReadinessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
